<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="2" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="43523" started-at="2021-01-12T12:59:08Z" finished-at="2021-01-12T12:59:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="43523" started-at="2021-01-12T12:59:08Z" finished-at="2021-01-12T12:59:52Z">
      <class name="com.trivago.automationframework.trivago.LoginTest">
        <test-method status="PASS" signature="baseBeforeClass()[pri:0, instance:com.trivago.automationframework.trivago.LoginTest@71d44a3]" name="baseBeforeClass" is-config="true" duration-ms="13032" started-at="2021-01-12T12:59:08Z" finished-at="2021-01-12T12:59:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- baseBeforeClass -->
        <test-method status="FAIL" signature="requirementTwo()[pri:0, instance:com.trivago.automationframework.trivago.LoginTest@71d44a3]" name="requirementTwo" duration-ms="30405" started-at="2021-01-12T12:59:21Z" finished-at="2021-01-12T12:59:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Azaya Beach Resort Goa Not Found expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Azaya Beach Resort Goa Not Found expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.trivago.automationframework.trivago.LoginTest.requirementTwo(LoginTest.java:100)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- requirementTwo -->
        <test-method status="PASS" signature="methodAfterClass()[pri:0, instance:com.trivago.automationframework.trivago.LoginTest@71d44a3]" name="methodAfterClass" is-config="true" duration-ms="54" started-at="2021-01-12T12:59:51Z" finished-at="2021-01-12T12:59:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- methodAfterClass -->
      </class> <!-- com.trivago.automationframework.trivago.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
